-- 1. What are the names of all the countries in the country table?
select country_name from country_insights;

-- 2. What is the total number of customers in the customers table?
select count(distinct customer_id) as customers_count from customers_insights;

--or 

select count(*) as customers_count from customers_insights;

-- 3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')? 
select avg(age) as customers_avg_age from customers_insights
where can_email = 'Yes';

-- 4. How many orders were made by customers aged 30 or older?
select c.customer_id,count(o.order_id) as customers_orders from customers_insights as c
join orders_insights as o
on o.customer_id = c.customer_id
where c.age > 30
group by c.customer_id;

-- 5. What is the total revenue generated by each product category?
select p.category , sum(p.price) as revenue_generated from products_insights as p
join baskets_insights as b
on p.product_id = b.product_id
group by  p.category 

-- 6. What is the average price of products in the 'food' category?
select avg(price) as avg_price_food from products_insights 
where category = 'food';

-- 7. How many orders were made in each sales channel (sales_channel column) in the orders table?
select sales_channel , count(order_id) as order_count from orders_insights
group by sales_channel;

-- 8. What is the date of the latest order made by a customer who can receive marketing emails?
select o.customer_id,max(o.date_shop) over(order by o.date_shop desc) as latest_order 
from orders_insights as o
join 
customers_insights as c
on o.customer_id = c.customer_id
where c.can_email='Yes'


-- 9. What is the name of the country with the highest number of orders?

select c.country_name , count(o.order_id) as order_count from country_insights as c
join orders_insights as o
on c.country_id = o.country_id 
group by c.country_name
order by order_count desc;

-- 10. What is the average age of customers who made orders in the 'vitamins' product category?
select avg(c.age) as avg_age from customers_insights as c
join orders_insights as o
on c.customer_id= o.customer_id
join baskets_insights as b
on b.order_id = o.order_id
join products_insights as p
on p.product_id = b.order_id
where p.category = 'vitamins';